name: Core

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
        
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Build gradle app:assembleDebug
      run: |
        gradle_version="7.5"
        base_dir="apps/zxtune-android"
        
        mkdir -p "$GITHUB_WORKSPACE"
        [ -n "$base_dir" ] && cd "$base_dir"
        
        export SIGNING_STORE_DIR="$RUNNER_TEMP/keystore"
        export SIGNING_STORE_FILE="$SIGNING_STORE_DIR/example.com.jks"
        export SIGNING_STORE_PASSWORD="changeit"
        mkdir -p "$SIGNING_STORE_DIR"
        export SIGNING_KEY_ALIAS="example.com"
        export SIGNING_KEY_DNAME="CN=$SIGNING_KEY_ALIAS, OU=Example Org, O=Example Company, L=San Francisco, ST=California, C=$US"
        export SIGNING_KEY_PASSWORD="changeit"
        export ANDROID_NDK_LATEST_HOME="$ANDROID_NDK_HOME"
        export KEYSTORE="$SIGNING_STORE_FILE"
        export NDK_DIR="$ANDROID_NDK_HOME"
        export NDK_ROOT="$ANDROID_NDK_HOME"
        export NDK_VER="${NDK_ROOT##*/}"
        CRLF=$'\r\n'
        
        keytool -genkeypair -v \
              -alias       "$SIGNING_KEY_ALIAS" \
              -dname       "$SIGNING_KEY_DNAME" \
              -keystore    "$SIGNING_STORE_FILE" \
              -keypass:env   SIGNING_KEY_PASSWORD \
              -storepass:env SIGNING_STORE_PASSWORD \
              -keyalg EC -keysize 256 -validity 385
              
        echo "$SIGNING_STORE_PASSWORD$CRLF" \
          | keytool -keystore "$KEYSTORE" \
              -keypass:env    SIGNING_KEY_PASSWORD \
              -storepass:env  SIGNING_STORE_PASSWORD \
              -importkeystore \
              -srckeystore  "$SIGNING_STORE_FILE" \
              -destkeystore "$SIGNING_STORE_FILE" \
              -deststoretype pkcs12
        {
          echo "storeFile=$SIGNING_STORE_FILE";
          echo "storePassword=$SIGNING_STORE_PASSWORD";
          echo "keyAlias=$SIGNING_KEY_ALIAS";
          echo "keyPassword=$SIGNING_KEY_PASSWORD";
        } | tee keystore.properties \
          ;
        {
          echo -e '\n';
          echo "android.ndkVersion=$NDK_VER";
          echo "Pkg.Revision=$NDK_VER";
          echo "Pkg.Name=android.ndk";
          echo -e '\n';
        } | tee -a "$ANDROID_NDK_HOME/source.properties" \
          | tee -a "$ANDROID_NDK_ROOT/source.properties" \
          | tee -a "local.properties" \
          ;
        {
          echo -e '\n';
          echo "android.ndkVersion=$NDK_VER";
          echo -e '\n';
        } | tee -a local.properties \
          ;
        {
          echo -e '\n';
          echo "org.gradle.caching=true";
          echo "org.gradle.parallel=true";
          echo "org.gradle.vfs.watch=false";
          echo -e '\n';
        } | tee -a gradle.properties
        
        if [ ! -e gradlew ]; then
          (
          echo QlpoOTFBWSZTWSOXsPYAAwN/gFRQQAJ////7///f7////+5gCZ3d8vPYe7cMOm8B7dOHXrRyGmta
          echo 9dDBiSNTEGQp7RTwmnqm0no0wU2poyHoCGmQGgAaAaCJhMjU01T9NKemiaaGgBk0PSAAA0Bo0AaB
          echo oCIaoBoBppoAAGg0AAAAAAAEhUKbRoJqejSYyT1GgGjQGhoADQGIepoNADgaNGINGmTCDEBiMTRo
          echo 0aANNNAAAAEiIQJomEyYmhKfqaT2pPJHqB6RoaAeoA0eoAxPUtLyjSBH19Rn4JuOzhD/Y8Wff3M2
          echo hqKu3whfuuUSX6ZlIr+o3oqifQZSGMbzw955GJpCZhQQDvKLhFgroUy781cwzKBW/mpLb1IzIHFL
          echo msXbWPDF+PBAQwbioiPsgyKlInWZdc8bqu+/3PAL75+O47hCAKCBaWkBv7IJZ89uL5fgZnOEPgXb
          echo PqKO6lO61zKn2kGAILhljyxUrWE8ocFdbJkEMd2QE3KcEB8VkE4WhlrRUe1tagMF+AkWC9ATOriy
          echo fyFy8NqThwuj6eqKMP4KXXa6LH6SqWRruOyWqwvr5pgQtlEnUhtR9cm4ZU/s3nDaZMRWc3fW2K1y
          echo rjhWcUFoVV1OgrHQxs7WeGt1p0wPNZB4bmXHtMIjMxoF+Z6W0uaKTvsb+KuOsQWA2GTaiJ+4PdYr
          echo k/iXaRI+NiVGgQy/0lyY6i3HJg4KMEuJ7aWKTjMHc5VSOOCvbfa8ZBWneEMy7W8kJC+LAwHOiaM4
          echo tFDaVB1VTiQ9C6LX5sJ2W3rLkMbrRjJ/YXT4CAccHwDw7/JafKcEbZyamFoKKCWqahqT0WriA65U
          echo mwQCdo2QnNWUWZstCaMCSGkEsHI6gPrySbLgxnN2ruPQlxPvcU3HAzbuSpBb8zoMfxs8gbCVPucY
          echo ADKRd8F7yHwA2S+I+WaugtVNnDL4/nSlKUpSmkdTETBL2X2/bEbOxqV72Wjub1xZWyNKOMGNNtqS
          echo BGgFGGSWUqns1xFTGy5va+XBo9XvS7buDBtsHUetHSG/fI02G+1QxNgUHD8aCgXU1CyyDGFjahBv
          echo PIDYNMbAkmuwQpxsmwPYQEUHMuaDM+jYq2WihS2F8nDkWrtYy1WB+unJvZc2fRp3MB2N+XDPXg09
          echo dFweEQqeO9Fn4XZIcpIpX0ARmxTOKAQPjReiiiUUo2Glt2o3Erc2J8Dht3LuAVtdK0E5CXHqs3q1
          echo uqOlOMlyTKUrD4cr+SFMJlzkQVx71PooFYCwJiAuC5AcNaAAfIff43Ini4YwwJjIHnjMUBTI9pCQ
          echo zB8mKIjqEHKKhBxqEi2gOlEXkCNsC5dcStGvPoOlnNRkUJfRolaPlpRJ8Ul/ZtRb9unz87pQE1mi
          echo RisRHaTgBgnAZqfIONTWc/hg7PGvkGRI4DiEGmXjdEaKRgRdH+jSeR3hGvZH/Urr8m1C2D1LNmMG
          echo 5kzEPDLki2vQK5YBwwA2NB4BtPA+iq0C6jrvOBUYZfTtOsRJ1i9wt4Twob6xTP7m7qDWGSSgtphr
          echo t8dlNyLbaK1Oyv7Tau03EUBoaMxrTe1GqAkXlVfUWW1hyPB4y19PhBnoS7ULW22XdE8D5eappg1B
          echo N7ujueBJZ96Syu76o54gXSPBGrh1RlnVnO5ryFqBXLbiReB4guVSVcLPA2hcLEegWJk9N5apsRp1
          echo qlzVFh2OeD2WKbK6QSU5FQCAQCrXtyWFaQsBOAU3S3hApFmGW60MgI2USYXI1tei5UIxhd1Ur0QJ
          echo 84uaMjXqHoIS97wOmkA43SOYA9EcVsCoOwEWXIhtsa1ToKVNlOSRkrR293saNOqy36slB2jxijMQ
          echo wgx+SsapKoQaIvpe8HJO6WtsDilvFahyGU0GcCJoKMmPRB7mMxz+S1aA1Pv/dPrBpoSGGRK69Jv7
          echo RrIovfu046vayiRcFR4xJtuNR6mxojgWwSPy0R4r9iOX+KcR0NnaUVDL2eyhepOkoP1vcsjIFcsq
          echo 5A2i/JFlOkH2mjO6xr3w3PO+J5WiZ0IGBjDVUCGRnVERjzhQ4V23VgKV5C+a6pJM7gYfmBCPI1EX
          echo VxDdCYeaIOgzj4PgUod81uuLKzALuaZapvu3rs8SQzg1adwzpJ1Ak4QO6wuUKJ30ENQxsgZGEmDg
          echo ekb0QTx2o3hVVrUMOc92rUNUXy3d58BfwjOy7PlLTZY0AkwICwFrxEQyY2Ar1J+ATiQzl+NnLiXS
          echo 9evFfLousIPrlUfkL9beD6D5amC87Z6Q9K+PvxDHm2NXmIZWgo2MIZjXw2NNNrm/hnXVXe0V3qbd
          echo 2JgALBhZHXtfSEjuByMFGJORCs55FSgZQ+f/dsFtVM0scOVp4DYZWReIB83U36LSeS6XYSEl5vCr
          echo ppcnZvYAsFXtCa0G3vaGjyTRvu9HpZHHtLRklganJzaTaJR1rqZxLaxt6KDNbDI6YVxM7Ljgu48X
          echo 4st2NMdWbFwG22ealZNM8dysLiuobF9svmuXxBnnFDJHmXTbNFbVBB8B3lc/Pjjgi9Bh7YxpRHzt
          echo 6Fy0HZvgIGoAslwgBU4sASFtzAWfXyX3NBamucQYZBDQzEN+2RNIsRSFEzI5hy0EyQDYUdqnD0ar
          echo /mdzJYRCwhhgQBQ14Wol+a4nds2bPKgWF360GJKgjDGhyghzjMmsLHo7KoGKlo6DLMypUVPl6Uvh
          echo mqjSgsHWSLJUMVYIwj2jxbGx1NEy1ce4vPNaqtZHAY+XZOcxBhCObtSvy4CWYtWvGOOckIKTJ32T
          echo CnnhNlUGPqCu/lpviDSELyIJLN4YqixG2JlULTRE1IrGeYvod3bXXstlrvmtYXL7HfrC9NJCyNk0
          echo vRonJXJmI2TL1UiYbwSxJFNIGFNp9NfBTKhqNQIIQhGLtJ5jr0xHnzR49bwQRdRfPJiZe/E5+Xzd
          echo hRXoOw44KCPsRBRUbVntrUmiQfEm3FywVCc9gxRYBo3UJGgwLyqi8iDSzpWek5OvCu6KDAegrNLT
          echo Y06cAkqULueIzGqDAd2petiAhrApopZyFGpTydgCFKzxlfIHQ78w8+Jtz9Hw9S79G/rSf0cHZU6e
          echo zUjTyFkFbuCzwxnOooFzw4aTQcNPNEgmovUmvblUmsE1fwX7fw+HaYeueB1tptvHc/RbndDWdBYU
          echo 0/cZCAsCxFpu7VYV2tg50BNKDO9xcdaw6EGnP/F3JFOFCQI5ew9g
        ) | base64 -d | bzip2 -dc > gradlew
        fi
        if [ ! -e gradle/wrapper/gradle-wrapper.jar ]; then
          mkdir -p gradle/wrapper \
            && curl -kvL -A "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36" "http://www.java2s.com/Code/JarDownload/gradle-wrapper/gradle-wrapper.jar.zip" > "gradle-wrapper.jar.zip" \
            && unzip -o "gradle-wrapper.jar.zip" -d gradle/wrapper "gradle-wrapper.jar" \
            && rm -f "gradle-wrapper.jar.zip"
        fi
        if [ ! -e gradle/wrapper/gradle-wrapper.properties ]; then
          mkdir -p gradle/wrapper \
            && (
              echo "#Tue May 24 19:03:21 IST 2022"
              echo "distributionBase=GRADLE_USER_HOME"
              echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-7.5-bin.zip"
              echo "distributionPath=wrapper/dists"
              echo "zipStorePath=wrapper/dists"
              echo "zipStoreBase=GRADLE_USER_HOME"
            ) > gradle/wrapper/gradle-wrapper.properties
        fi
        chmod a+rx gradlew
        
        [ -z "$gradle_version" ] && gradle_version="$( curl -ks "https://gradle.org/releases/" | sed -r -e '\~v[0-9]|ver~I s~^.*[^0-9.]([0-9.]+[.][0-9])".*$~\1~Igp;d' | head -1; )"
        url="https://services.gradle.org/distributions/gradle-${gradle_version}-bin.zip"
        IFS=$'\n'; set -- $( find "${GITHUB_WORKSPACE:-.}" -name gradle-wrapper.properties );
        for pfile in "$@"; do
          echo "Updating [$pfile] to gradle version [${gradle_version}] .. " 1>&2
          sleep 1 || true
          sed -r -e "\\!(distributionUrl)=.*!{ s!!\\1=${url}!; s!:!\\\\:!g; w /dev/stderr" -e "}" -i.bak -- "$pfile"
          echo "[ $? ] Updating [$pfile]" 1>&2
          sleep 1 || true
        done
        
        ./gradlew app:assembleDebug \
          || ./gradlew

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: |
          app/build/outputs/apk/debug/*.apk
       
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: |
          ./*
          ./**
          build
          build/*
          build/**
          buildRelease
          buildRelease/*
          buildRelease/**
          module
          module/*
          module/**
          $GITHUB_WORKSPACE/**
          